### ISSUE TITLE
Misformed URL 404

### ISSUE THREAD

**Issue by kellrott** [ohsu-comp-bio/funnel#282] opened 2017-10-30 23:37 UTC
When creating a task with a bad URL ( POST http://funnel.my.host//v1/tasks ) I get back a list of tasks rather than a 404.

**Comment by adamstruck** [comment] 2017-10-31 16:03
I can also reproduce this with `funnel run -S http://localhost:8000// --sh "echo hello"`

**Comment by buchanae** [comment] 2017-11-10 19:29
I can't reproduce this, I think it was fixed in #292

**Closed by buchanae** 2017-11-10 19:29 UTC
Labels: bug
