### ISSUE TITLE
Funnel webpage becomes unresponsive

### ISSUE THREAD

**Issue by kmavrommatis** [ohsu-comp-bio/funnel#608] opened 2019-04-03 20:57 UTC
When I have multiple jobs running or queued up the web page of funnel becomes unresponsive. This is not the case when all jobs are in ERROR or COMPLETED state.
I attribute that partly to the web browser used (Firefox is more responsive than Chrome for example), but also to the number of jobs that the web server is trying to show.

Is there any setting that can alter this behaviour? 

Is it possible to paginate the results, e.g. show only the top N jobs in the system? Currently there does not seem to be a limit and the web page is trying to show all tasks.

Is there any automatic way to flush old tasks from the database so that they don't show up in the list (e.g. tasks older than 1month?). Conceivably, I can run a cron job that cleans up the backend database (mongodb in this case) of old tasks, but I was wondering if something like that already exists.

Thanks

**Comment by adamstruck** [comment] 2019-04-04 19:55
The dashboard does paginate the results (256 tasks are fetched per page). I was able to reproduce the issue you describe here locally. I'm not sure what is causing this issue, the dashboard worked well for us in the past. I suspect it has something to do with the browser caching the dashboard is doing. 

We have not provided any functionality for removing old tasks from the database.

**Comment by adamstruck** [comment] 2019-04-04 20:30
I created an experimental branch that seems to address this issue: https://github.com/ohsu-comp-bio/funnel/tree/webdash-no-autorefresh

I removed the auto-refresh, response caching and reduced the page size to 50.

**Comment by kmavrommatis** [comment] 2019-04-05 13:36
Thanks, that works much better now. 

Would it be possible to  add a couple more elements on the ui such as  a 'Previous page' button and perhaps a counter to indicate which page the user is viewing? 

Thanks again for your help

**Comment by adamstruck** [comment] 2019-04-10 20:10
I don't currently have the bandwidth to add those features.  The previous page can be accessed via the back button in your browser. Since our paging system is token based it would require a bit of work to determine the total number of pages available.

**Comment by adamstruck** [comment] 2020-01-17 23:52
fixed by #610

**Closed by adamstruck** 2020-01-17 23:52 UTC
